[package]

name = "heredoc"
version = "0.0.1"
authors = ["Jorge Israel Pe√±a <jorge.israel.p@gmail.com>"]
description = "a heredoc implementation"
repository = "https://github.com/blaenk/heredoc"
license = "BSD-3-Clause"

[lib]
name = "heredoc"
path = "src/lib.rs"
plugin = true
